bootstrap.servers=localhost:29092
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=sbp.school.kafka.utils.deserializer.HashSumJSONDeserializer
enable.auto.commit=false
group.id=backFlow

kafka.hashSum.topic.name=hashSum-topic
kafka.producer.topic.name=transactions-topic