#Consumer settings
bootstrap.servers=localhost:29092
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=sbp.school.kafka.utils.deserializer.TransactionJSONDeserializer
enable.auto.commit=false
group.id=transactions

#BackFlowProducer settings
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=sbp.school.kafka.utils.deserializer.HashSumJSONSerializer
acks=all

#Back flow topic name
kafka.hashSum.topic.name=hashSum-topic

#Transaction topic name
kafka.producer.topic.name=transactions-topic

#?????????? ??????? ? ??????? ?? ??????? ??????? ?????? ? ??
db.interval=10